##############################################################################
# Publish workflow unit tests for ansibleRunner.
#
# USAGE:
#   python3 -m pytest tests/unit/testPublishWorkflow.py
#
# WORKFLOW:
#   1. Verify release versions are read from pyproject.toml.
#   2. Verify dirty worktrees prevent publishing.
#   3. Verify the publish command sequence pushes the tag and release assets.
#
# Copyright 2026 Douglas WF Acheson (dwfa@dwfa.ca)
# Licensed under Apache License 2.0. See LICENSE.md for details.
#
# Version: 1.0
# Date: August 04, 2026
##############################################################################

from __future__ import annotations

import importlib.util
import subprocess
import sys
from pathlib import Path
from typing import Any

import pytest


def testReadProjectVersionUsesPyprojectMetadata(tmp_path: Path) -> None:
    """Verify publish.py reads the release version from pyproject.toml."""

    publish = _loadPublishModule()
    pyprojectPath = tmp_path / "pyproject.toml"
    pyprojectPath.write_text(
        "\n".join(
            [
                "[project]",
                'name = "ansibleRunner"',
                'version = "1.2.3"',
            ]
        ),
        encoding="utf-8",
    )

    assert publish.readProjectVersion(tmp_path) == "1.2.3"


def testRequireCleanWorktreeRejectsDirtyStatus(
    monkeypatch: Any,
    tmp_path: Path,
) -> None:
    """Verify uncommitted files block publishing."""

    publish = _loadPublishModule()

    def fakeRunCommand(
        command: list[str],
        cwd: Path,
        dryRun: bool = False,
        mutates: bool = False,
    ) -> subprocess.CompletedProcess[str]:
        """Return dirty git status output."""

        del command, cwd, dryRun, mutates
        return subprocess.CompletedProcess([], 0, stdout=" M README.md\n", stderr="")

    monkeypatch.setattr(publish, "runCommand", fakeRunCommand)

    with pytest.raises(SystemExit) as exc:
        publish.requireCleanWorktree(tmp_path)

    assert "dirty worktree" in str(exc.value)
    assert "README.md" in str(exc.value)


def testPublishReleasePushesTagAndAssets(
    monkeypatch: Any,
    tmp_path: Path,
) -> None:
    """Verify publish.py builds the expected git and gh release commands."""

    publish = _loadPublishModule()
    calls: list[list[str]] = []

    def fakeRunCommand(
        command: list[str],
        cwd: Path,
        dryRun: bool = False,
        mutates: bool = False,
    ) -> subprocess.CompletedProcess[str]:
        """Capture publish commands."""

        del cwd, dryRun, mutates
        calls.append(command)
        return subprocess.CompletedProcess(command, 0, stdout="", stderr="")

    monkeypatch.setattr(publish, "runCommand", fakeRunCommand)
    context = publish.PublishContext(
        dryRun=False,
        projectRoot=tmp_path,
        tagName="v1.2.3",
        version="1.2.3",
    )
    wheelPath = tmp_path / "dist" / "ansiblerunner-1.2.3-py3-none-any.whl"

    publish.publishRelease(context, wheelPath)

    assert calls == [
        ["git", "tag", "-a", "v1.2.3", "-m", "Release 1.2.3"],
        ["git", "push", "origin", "v1.2.3"],
        [
            "gh",
            "release",
            "create",
            "v1.2.3",
            str(tmp_path / "install.py"),
            str(wheelPath),
            "--title",
            "ansibleRunner v1.2.3",
            "--notes",
            "## ansibleRunner 1.2.3\n\n"
            "Release generated by scripts/publish.py.\n",
        ],
    ]


def _loadPublishModule() -> Any:
    """Load scripts/publish.py as an importable test module."""

    scriptPath = Path(__file__).resolve().parents[2] / "scripts" / "publish.py"
    spec = importlib.util.spec_from_file_location("ansibleRunnerPublishScript", scriptPath)
    assert spec is not None
    assert spec.loader is not None

    module = importlib.util.module_from_spec(spec)
    sys.modules[spec.name] = module
    spec.loader.exec_module(module)
    return module
